boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 10173ac0-034d-45d8-745c-1e43bda57f6e
  sha: sha256:47f11c8844e579d02691a607fbd32540104a9ac7a2534a8ddaef50daf502baac
check/check-0.10.0.orig.tar.gz:
  size: 769119
  object_id: ef7b3921-91ac-4dfb-45a7-65bc836eb307
  sha: sha256:f5f50766aa6f8fe5a2df752666ca01a950add45079aa06416b83765b1cf71052
libaio/libaio_0.3.110.orig.tar.gz:
  size: 42270
  object_id: ffce712d-c4f3-4a3b-764a-42f949b43ad3
  sha: sha256:e019028e631725729376250e32b473012f7cb68e1f7275bfc1bbcdd0f8745f7e
libev/libev-4.33.tar.gz:
  size: 569527
  object_id: 0ea3b0f6-7b83-4fe5-7ff8-966bcc56ab73
  sha: sha256:507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
pxc/Percona-XtraDB-Cluster-5.7.41-31.65.tar.gz:
  size: 87286647
  object_id: 8c39a8a9-99e6-404f-6470-9965a7736d4a
  sha: sha256:a873656a5eabd2857bf675bcbcc3f45a205243db7dca26e5de397535c45371d9
socat/socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: cb399cd1-9dc2-4207-44ba-f055a4c3eada
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
xtrabackup/percona-xtrabackup-2.4.28.tar.gz:
  size: 62525343
  object_id: 96620161-c2d0-4283-7f31-fcf184e02597
  sha: sha256:1d77f920a0cf536e12ddcd3a154583b1b52cd3db35bd2d06db629cc255367cea
