Percona-XtraDB-Cluster-5.7.40-31.63.tar.gz:
  size: 87272177
  object_id: 0094e4f2-587b-42c2-5b0b-dfbc8325a08f
  sha: sha256:b989462d47f8bec81b807a1beb6feccedbe56fba577c892d1cceb51857e695d8
Percona-XtraDB-Cluster-8.0.30-22.tar.gz:
  size: 565361265
  object_id: 90f42b1b-9ee4-4175-708e-f24f0289b01a
  sha: sha256:e514748262a811a90d60abd1ee3bf8f5cdea02538f79b6f124329acc18acda7b
boost_1_59_0.tar.bz2:
  size: 70389425
  object_id: 7344fc77-b911-45c2-5467-c6d5fcab6d29
  sha: sha256:727a932322d94287b62abb1bd2d41723eec4356a7728909e38adb65ca25241ca
boost_1_77_0.tar.bz2:
  size: 110361537
  object_id: d962752f-1ab7-4896-41d9-8deed29397ca
  sha: sha256:fc9f85fc030e233142908241af7a846e60630aa7388de9a5fafb1f3a26840854
check_0.15.2.orig.tar.gz:
  size: 773805
  object_id: d1c4eec5-21ea-433c-6572-7ca6a1e60f5b
  sha: sha256:8451b68ac5d6f3157b24f22eceff575bcf566264f6d78f3852f89d4e08cf42e1
libaio_0.3.112.orig.tar.xz:
  size: 38196
  object_id: 882ebd2d-d1ec-43f2-796e-3060030a4474
  sha: sha256:f69e5800425f4ea957426693ac09f9896bb993db5490fa021644454adcc72a32
libev-4.33.tar.gz:
  size: 569527
  object_id: 0ea3b0f6-7b83-4fe5-7ff8-966bcc56ab73
  sha: sha256:507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
percona-xtrabackup-2.4.27.tar.gz:
  size: 62521070
  object_id: 9cbca57d-0e12-4d6f-784c-534c302562e5
  sha: sha256:1b92dba25749834ae3b79ddc37859659970996e2962d2f3b752470da4f4f69db
percona-xtrabackup-8.0.30-23.tar.gz:
  size: 338259133
  object_id: 9699b14f-d311-453f-51f4-163aebfc5570
  sha: sha256:9b1bfb1cce2860627aebed53d62e86b55e657869c91b715f626c20759b7341eb
procps_3.3.17.orig.tar.xz:
  size: 1008428
  object_id: 49ca152b-47d2-4737-5f55-154159b7ed7d
  sha: sha256:4518b3e7aafd34ec07d0063d250fd474999b20b200218c3ae56f5d2113f141b4
socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: beda2a1f-82fe-4370-47c9-080352292869
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
