boost/boost_1_59_0.tar.gz:
  size: 83709983
  object_id: 10173ac0-034d-45d8-745c-1e43bda57f6e
  sha: sha256:47f11c8844e579d02691a607fbd32540104a9ac7a2534a8ddaef50daf502baac
check/check-0.10.0.orig.tar.gz:
  size: 769119
  object_id: ef7b3921-91ac-4dfb-45a7-65bc836eb307
  sha: sha256:f5f50766aa6f8fe5a2df752666ca01a950add45079aa06416b83765b1cf71052
libaio/libaio_0.3.110.orig.tar.gz:
  size: 42270
  object_id: ffce712d-c4f3-4a3b-764a-42f949b43ad3
  sha: sha256:e019028e631725729376250e32b473012f7cb68e1f7275bfc1bbcdd0f8745f7e
libev/libev-4.33.tar.gz:
  size: 569527
  object_id: 0ea3b0f6-7b83-4fe5-7ff8-966bcc56ab73
  sha: sha256:507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
pxc/Percona-XtraDB-Cluster-5.7.36-31.55.tar.gz:
  size: 86976230
  object_id: f0da486d-db8c-472a-6ead-c977637c24ed
  sha: sha256:85c6954eb7b9ed59ced68c0da545bd1405f7298236caa0af490131ff0e95d62e
scons/scons-3.0.1.tar.gz:
  size: 634815
  object_id: aee42c31-779f-4b55-70e0-93a4ddd5e872
  sha: sha256:24475e38d39c19683bc88054524df018fe6949d70fbd4c69e298d39a0269f173
socat/socat-1.7.4.1.tar.gz:
  size: 648888
  object_id: f0547b7c-9f0d-4193-5f65-c3f85f76ec02
  sha: sha256:0c7e635070af1b9037fd96869fc45eacf9845cb54547681de9d885044538736d
xtrabackup/percona-xtrabackup-2.4.25.tar.gz:
  size: 62014901
  object_id: 91b7f0c2-f5ff-4f14-76fc-dd6e8756cb8f
  sha: sha256:10bdeabe61404bcc261d7467f547953fff7c9752c39ddc2e09fdc537997cc794
