Percona-XtraDB-Cluster-5.7.44-31.65-5.tar.gz:
  size: 73188463
  object_id: 884878f7-0825-481a-5d2b-9e2b02c72168
  sha: sha256:2a9266599b8827b51e7130b12184805e27e0b15c0178777e9e1f8f90155d4622
Percona-XtraDB-Cluster-8.0.44-35.tar.gz:
  size: 529799158
  object_id: 1636042c-aa5f-47c5-75e3-973440644229
  sha: sha256:0bd17bb930c0bf2e0bd5857ef12e547663658d7c9abfac99ff097daf9d74d488
Percona-XtraDB-Cluster-8.4.6-6.tar.gz:
  size: 506765745
  object_id: ec442812-58d7-4ff8-616a-6e72be3d6a56
  sha: sha256:1b8ae8266c223b34330a54d4af76f7e10d0b0875ac51041bad0e02e95fa47fd4
boost_1_59_0.tar.bz2:
  size: 70389425
  object_id: 7344fc77-b911-45c2-5467-c6d5fcab6d29
  sha: sha256:727a932322d94287b62abb1bd2d41723eec4356a7728909e38adb65ca25241ca
boost_1_77_0.tar.bz2:
  size: 110361537
  object_id: d962752f-1ab7-4896-41d9-8deed29397ca
  sha: sha256:fc9f85fc030e233142908241af7a846e60630aa7388de9a5fafb1f3a26840854
check_0.15.2.orig.tar.gz:
  size: 773805
  object_id: d1c4eec5-21ea-433c-6572-7ca6a1e60f5b
  sha: sha256:8451b68ac5d6f3157b24f22eceff575bcf566264f6d78f3852f89d4e08cf42e1
jemalloc-5.3.0.tar.bz2:
  size: 736023
  object_id: 3de075b1-afbb-47d4-4bbd-0cc130b02431
  sha: sha256:2db82d1e7119df3e71b7640219b6dfe84789bc0537983c3b7ac4f7189aecfeaa
libaio_0.3.112.orig.tar.xz:
  size: 38196
  object_id: 882ebd2d-d1ec-43f2-796e-3060030a4474
  sha: sha256:f69e5800425f4ea957426693ac09f9896bb993db5490fa021644454adcc72a32
libev-4.33.tar.gz:
  size: 569527
  object_id: 0ea3b0f6-7b83-4fe5-7ff8-966bcc56ab73
  sha: sha256:507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea
percona-xtrabackup-2.4.29.tar.gz:
  size: 64667518
  object_id: f196e2a0-e2ba-43ef-7d91-4319f8e6b927
  sha: sha256:c59f0d612ec6a0f530ca3645546fb8af690f62d3ecbd70d33f30d3f56d9e842e
percona-xtrabackup-8.0.35-34.tar.gz:
  size: 447840968
  object_id: 7fd5dc55-cf98-40e3-7505-0854a918327d
  sha: sha256:6ca81cd647e7cb1d8fd341f97cd32248bd719f9104a63eb24f1edda6a2d2441c
percona-xtrabackup-8.4.0-4.tar.gz:
  size: 432657062
  object_id: 036a8d00-269f-4e54-627d-e1ad7be215e4
  sha: sha256:e566a164a21b18781aad281b84426418ac2bcf71052ec85d8c5e62f742a7dfeb
pkg-config_0.29.2.orig.tar.gz:
  size: 2016830
  object_id: ca3d829d-016e-4acd-6509-9d1766884b9d
  sha: sha256:6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
procps-ng-4.0.5.tar.xz:
  size: 1517672
  object_id: e196e815-f7be-462d-64f0-feaac1caffe0
  sha: sha256:c2e6d193cc78f84cd6ddb72aaf6d5c6a9162f0470e5992092057f5ff518562fa
socat-1.7.4.4.tar.gz:
  size: 662968
  object_id: beda2a1f-82fe-4370-47c9-080352292869
  sha: sha256:0f8f4b9d5c60b8c53d17b60d79ababc4a0f51b3bb6d2bd3ae8a6a4b9d68f195e
